-- Einsatzzeit & Anfahrt (HH:MM als VARCHAR(5))
ALTER TABLE protokolle
  ADD COLUMN einsatz_von VARCHAR(5) NULL DEFAULT NULL,
  ADD COLUMN einsatz_bis VARCHAR(5) NULL DEFAULT NULL,
  ADD COLUMN anfahrt_km INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN anfahrt_minuten INT UNSIGNED NULL DEFAULT NULL;
